name: Build OpenWRT
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      openwrtRelease: 22.03.2
      gcc: gcc-11.2.0
      workingDirectory: ${{ github.workspace }}/openwrt
    steps:
    - uses: actions/checkout@v2
    
    - name: Actions Status Discord
      # You may pin to the exact commit or the version.
      # uses: sarisia/actions-status-discord@2947ebd8725337da402c454d25063e48e754f793
      uses: sarisia/actions-status-discord
      with:
        # Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used.
        webhook: ${{ secrets.discordWebhook }}
        # Job status. Should be bound to job.status. Default to success.
        status: # optional, default is ${{ job.status }}
        # Deprecated. Job name included in message title. Same as title input.
        job: # optional
        # Content. Shown as an message outside of the embed. See [Mention to user/role](#mention-to-user-role)
        content: # optional
        # String included in embed title. Overrides job input.
        title: # optional, default is ${{ github.workflow }}
        # Description included in message
        description: # optional
        # Image attached to the message
        image: # optional
        # Overrides Discord embed color
        color: # optional
        # URL to jump when the title is clicked
        url: # optional
        # Overrides Discord webhook username
        username: # optional
        # Overrides Discord webhook avatar url
        avatar_url: # optional
        # This action won't make workflow failed by default.
        nofail: # optional, default is true
        # Suppress GitHub context fields
        nocontext: # optional, default is false
        # Avoid appending job status to title
        noprefix: # optional, default is false
        # Suppress detailed embed fields
        nodetail: # optional, default is false
        # Avoid appending timestamp
        notimestamp: # optional, default is false
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -q -y upgrade
        sudo apt-get -q -y install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev
        sudo apt-get -q -y autoremove
        sudo apt-get -q -y autoclean
        sudo apt-get -q -y clean
        
    - name: Clone OpenWrt git repo
      run: |
        umask 0022
        git clone https://github.com/openwrt/openwrt.git
    
    - name: Checkout ${{ env.openwrtRelease }}
      run: git checkout ${{ env.openwrtRelease }}
    
    - name: Copy .config file
      run: cp .config ${{ env.workingDirectory }}
    
    - name: create diffconfig
      run: |
        ./scripts/diffconfig.sh > diffconfig
        cp diffconfig .config
    
    - name: Get version
      run: |
        VERSION=`cat version`
        echo OpenWrt version is $VERSION
        echo "##vso[task.setvariable variable=openwrtVersion]$VERSION"
    
    - name: Update package feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    
    - name: Print number of CPUs
      run: |
        NPROC=$(`nproc`+1)
        echo Number of CPUs is $NPROC
        df -h
    
    - name: make defconfig
      run: |
        export TERM=linux
        make -j$(`nproc`+1) defconfig
    
    - name: make download
      run: |
        export TERM=linux
        make -j$(`nproc`+1) download
    
    - name: Build the project
      run: |
        export TERM=linux
        make -j$(`nproc`+1)
    
    - name: Print disk space
      run: df -h
    
    - run: Copy '${{ env.workingDirectory }}/bin/targets/x86/64/*' '${{ github.workspace }}'
    - uses: actions/upload-artifact@v2
      with:
        path: 
        name: openwrt-${{ env.openwrtRelease }}-x86-64-APU2-${{ github.run_number }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.openwrtRelease }}_${{ github.run_number }}
    
    - name: Actions Status Discord
      # You may pin to the exact commit or the version.
      # uses: sarisia/actions-status-discord@2947ebd8725337da402c454d25063e48e754f793
      uses: sarisia/actions-status-discord@v1.11.0
      with:
        # Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used.
        webhook: ${{ secrets.discordWebhook }}
        # Job status. Should be bound to job.status. Default to success.
        status: # optional, default is ${{ job.status }}
        # Deprecated. Job name included in message title. Same as title input.
        job: # optional
        # Content. Shown as an message outside of the embed. See [Mention to user/role](#mention-to-user-role)
        content: # optional
        # String included in embed title. Overrides job input.
        title: # optional, default is ${{ github.workflow }}
        # Description included in message
        description: # optional
        # Image attached to the message
        image: # optional
        # Overrides Discord embed color
        color: # optional
        # URL to jump when the title is clicked
        url: # optional
        # Overrides Discord webhook username
        username: # optional
        # Overrides Discord webhook avatar url
        avatar_url: # optional
        # This action won't make workflow failed by default.
        nofail: # optional, default is true
        # Suppress GitHub context fields
        nocontext: # optional, default is false
        # Avoid appending job status to title
        noprefix: # optional, default is false
        # Suppress detailed embed fields
        nodetail: # optional, default is false
        # Avoid appending timestamp
        notimestamp: # optional, default is false
                    
